feat(install): adds an install script

diff --git a/placeos b/placeos
--- a/placeos
+++ b/placeos
@@ -56,16 +56,11 @@ set -euo pipefail
 # Kill child processes on signals
 trap 'tput cnorm; pkill -P $$;' SIGINT SIGTERM
 
-# Colours
-red='\033[0;31m'
-green='\033[0;32m'
-reset='\033[0m'
-
 # Whether to write to STDOUT or not
 VERBOSE="false"
 
 # Path of directory containing the script
-base_path="$(dirname "${0}")"
+base_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
 # Terminal spinner
 source "${base_path}/scripts/spinner.sh"
@@ -80,6 +75,14 @@ COMPOSE_PROJECT_NAME=placeos
 ###################################################################################################
 
 PROMPT="░░░"
+
+# Colours
+red='\033[0;31m'
+green='\033[0;32m'
+yellow='\033[0;33m'
+reset='\033[0m'
+bold='\033[1m'
+normal='\033[22m'
 
 unknown_argument() (
     unknown_arg="${1}"
@@ -140,7 +143,8 @@ hard_reset() (
     run_or_abort \
         'docker-compose restart nginx' \
         "Restarting nginx..." \
-        "Failed to restart nginx."
+        "Failed to restart nginx." \
+        "true"
 )
 
 start_environment__usage() (
@@ -227,7 +231,10 @@ start_environment() (
 
     prompt "Starting PlaceOS <${PLACEOS_TAG}>"
 
-    [ $VERBOSE == "false" ] && prompt "For detailed logging, run \`tail -f ${logfile}\`"
+    if [[ $VERBOSE == "false" ]]; then
+        prompt "For detailed logging, run..."
+        prompt "${bold}tail -f ${logfile}${normal}"
+    fi
 
     EMAIL_ENV="${base_path}/.env.email"
 
@@ -312,6 +319,13 @@ start_environment() (
         "Pulling images..." \
         "Failed to pull images."
 
+    [ ${hard_reset} == "true" ] && hard_reset
+
+    run_or_abort \
+        "${base_path}/scripts/run-init-container" \
+        "Initialising PlaceOS with default domain ($PLACE_DOMAIN)..." \
+        "Failed to create user entity."
+
     run_or_abort \
         "docker-compose ${PROFILES} up -d" \
         "Bringing up services..." \
@@ -324,15 +338,9 @@ start_environment() (
             "Failed to configure InfluxDB."
     fi
 
-    [ ${hard_reset} == "true" ] && hard_reset
-
-    run_or_abort \
-        "${base_path}/scripts/run-init-container" \
-        "Initialising PlaceOS with default domain ($PLACE_DOMAIN)..." \
-        "Failed to create user entity."
-
-    prompt "PlaceOS initialised. Login to https://$PLACE_DOMAIN/backoffice/ with..."
-    prompt "$PLACE_EMAIL:$PLACE_PASSWORD"
+    prompt "${green}PlaceOS initialised!${reset}"
+    prompt "Login to https://$PLACE_DOMAIN/backoffice/ with..."
+    prompt "${yellow}$PLACE_EMAIL${reset}:${yellow}$PLACE_PASSWORD${reset}"
 )
 
 # Stop
@@ -492,6 +500,7 @@ If VERSION is omitted, defaults to the most recent stable version.
 
 Arguments:
     --list                  List the available versions.
+    --restart               Restart services after updating, loading the new version.
     -v, --verbose           Write logs to STDOUT in addition to the log file.
     -h, --help              Display this message.
 EOF
@@ -499,6 +508,7 @@ EOF
 
 update_environment() (
     version=""
+    restart_services="false"
     while [ ${#} -gt 0 ]; do
         command="${1}"
         shift
@@ -510,6 +520,9 @@ update_environment() (
         --list)
             fetch_release_tags
             exit 0
+            ;;
+        --restart)
+            restart_services="true"
             ;;
         -v | --verbose)
             VERBOSE="true"
@@ -528,11 +541,11 @@ update_environment() (
     tags=$(fetch_release_tags)
 
     if [[ -z "$version" ]]; then
-        version=$(echo "$tags" | grep -Ev "$VERSION_CHANNEL_REGEX" | head -1)
+        version=$(grep -v --extended-regexp "$VERSION_CHANNEL_REGEX" <<<"${tags}" | head -1)
     fi
 
     # shellcheck disable=2076
-    if [[ -z "$(grep -E "$CALVER_FULL_REGEX|$CALVER_MONTH_REGEX|$VERSION_CHANNEL_REGEX" <<< $version)" ]]; then
+    if ! grep -q --extended-regexp "$CALVER_FULL_REGEX|$CALVER_MONTH_REGEX|$VERSION_CHANNEL_REGEX" <<<"$version"; then
         prompt "Valid versions are...\n\n$tags\n"
         abort "${version} is not a valid version."
     fi
@@ -542,18 +555,25 @@ update_environment() (
         "Updating to ${version}" \
         "Failed to update to ${version}"
 
-    changelog ${version}
+    if [[ $restart_services == "true" ]]; then
+        run_or_abort \
+            "docker-compose restart" \
+            "Restarting services on ${version}..." \
+            "Failed to restart services"
+    fi
+
+    changelog "${version}"
 )
 
 # Upgrade
 ###################################################################################################
 
-PARTNER_ENV_REPO="place-labs/partner-environment"
+PARTNER_ENV_REPO="placeos/partner-environment"
 
 fetch_environment_tags() (
     git ls-remote https://github.com/${PARTNER_ENV_REPO} |
         cut -f2 |
-        grep -E '^refs/tags/|HEAD' |
+        grep --extended-regexp '^refs/tags/|HEAD' |
         cut -d'/' -f3 |
         sort --version-sort --reverse
 )
@@ -567,14 +587,15 @@ If VERSION is omitted, defaults to the latest version.
 
 Arguments:
     --list                  Lists versions of the Partner Environment.
-    -v, --verbose           Write logs to STDOUT in addition to the log file.
+    -q, --quiet             Do not write command logs to STDOUT.
     -h, --help              Display this message.
 EOF
 )
 
 upgrade_environment() (
-    version=""
+    version="HEAD"
     tags="$(fetch_environment_tags)"
+    VERBOSE="true"
 
     while [ ${#} -gt 0 ]; do
         command="${1}"
@@ -588,8 +609,8 @@ upgrade_environment() (
             echo "$tags"
             exit 0
             ;;
-        -v | --verbose)
-            VERBOSE="true"
+        -q | --quiet)
+            VERBOSE="false"
             ;;
         -*)
             unknown_argument "${command}" "upgrade_environment__usage"
@@ -603,7 +624,7 @@ upgrade_environment() (
     done
 
     # shellcheck disable=2076
-    if [[ ! " $tags " =~ " $version " ]]; then
+    if [[ ! " $tags " =~ "$version" ]]; then
         prompt "Valid versions are...\n\n$tags\n"
         abort "$version is not a valid version."
     fi
@@ -620,10 +641,18 @@ upgrade_environment() (
 
     last_commit=$(git rev-parse "$version")
 
-    run_or_abort \
-        "git pull --autostash --quiet --rebase origin $version" \
-        "Upgrading PlaceOS Partner Environment..." \
-        "Failed to upgrade PlaceOS Partner Environment"
+    if ! git diff --quiet; then
+        (
+          git stash --include-untracked \
+            && git checkout --quiet "$version" \
+            && git stash apply
+        ) || abort "Failed to upgrade, you may need to resolve merge conflicts"
+    else
+        run_or_abort \
+            "git checkout --quiet $version" \
+            "Upgrading PlaceOS Partner Environment..." \
+            "Failed to upgrade PlaceOS Partner Environment"
+    fi
 
     # Check if it was really updated or not
     if [[ "$(git rev-parse HEAD)" = "$last_commit" ]]; then
@@ -631,6 +660,61 @@ upgrade_environment() (
     else
         prompt "PlaceOS Partner Environment is now at $version"
     fi
+)
+
+# Uninstall
+###################################################################################################
+
+uninstall_environment__usage() (
+    cat <<EOF
+Usage: placeos uninstall
+
+Removes PlaceOS containers, removes scripts from paths, and finally deletes the installation path.
+
+Arguments:
+    --force                 Skip confirmation of uninstall.
+    -h, --help              Display this message.
+EOF
+)
+
+uninstall_environment() (
+    force="false"
+    VERBOSE="true"
+
+    while [ ${#} -gt 0 ]; do
+        command="${1}"
+        shift
+        case ${command} in
+        -h | --help | help)
+            uninstall_environment__usage
+            exit 0
+            ;;
+        --force)
+            force="true"
+            ;;
+        *)
+            unknown_argument "${command}" "uninstall_environment__usage"
+            ;;
+        esac
+    done
+
+    # Get confirmation.
+
+    if [ "${force}" == "false" ]; then
+        read -rp "${PROMPT} $(echo -e "${red}Warning:${reset}") This will remove your PlaceOS installation. Would you like to continue (y/n)? " choice
+        case "${choice}" in
+        y | Y | YES | yes) ;;
+
+        *)
+            abort "Exiting."
+            ;;
+        esac
+    fi
+
+    # Stop environment.
+    # Remove PlaceOS containers.
+    # Remove scripts from paths.
+    # Delete the installation path.
 )
 
 # Root Command
@@ -645,9 +729,10 @@ Helper script for interfacing with the PlaceOS Partner Environment.
 Command:
     start                   Start the environment.
     stop                    Stops the environment.
+    task                    Runs a task in the environment.
     update                  Update the platform version.
     upgrade                 Upgrade the Partner Environment.
-    task                    Runs a task in the environment.
+    uninstall               Uninstalls the Partner Environment.
     help                    Display this message.
 
 Arguments:
